### ISSUE TITLE
Iphone 6 iOS 11.1.2 no Cydia

### ISSUE THREAD

**Issue by rezzifriaz** [iabem97/topanga#2] opened 2017-12-23 05:57 UTC

**Comment by iM4CH3T3** [comment] 2017-12-23 06:19
Can you please check if you have the bootstrap folder installed by this jailbreak ? For me it’s not. So it can’t even do anything because everything starts from the bootstrap folder :/

**Comment by iM4CH3T3** [comment] 2017-12-23 06:19
Location is in /

**Comment by HonestlyAnnoying** [comment] 2017-12-23 06:52
bootstrap is installed, but no Cydia icon

**Comment by rezzifriaz** [comment] 2017-12-23 07:16
No bootstrap folder,why ?

**Comment by Basputaek13** [comment] 2017-12-23 07:49
Follow

**Comment by Basputaek13** [comment] 2017-12-23 07:50
Follow

**Comment by iM4CH3T3** [comment] 2017-12-23 08:15
Because when no bootstrap folder the cydia.tar can’t be extracted and installed

**Comment by nullpixel** [comment] 2017-12-23 09:45
Hi there, we've closed this issue as a dupe of #1.

**Closed by nullpixel** 2017-12-23 09:45 UTC
