### ISSUE TITLE
No Cydia App Icon after Jailbreak in iPhone X on iOS 11.0.1

### ISSUE THREAD

**Issue by XIONGJUNHAN** [iabem97/topanga#63] opened 2017-12-26 05:07 UTC
No Cydia App Icon after Jailbreak in iPhone X on ios11.0.1 but the app mention me the iPhone was jailbreaked！

**Comment by Johntpeterson** [comment] 2017-12-26 05:25
This issue is a dupe of #29, please check the posted issues before opening a new one.

**Closed** 2017-12-26 05:29 UTC

**Comment by XIONGJUNHAN** [comment] 2017-12-26 05:33
thinks
		
		

		
	




On Tue, Dec 26, 2017 at 1:29 PM +0800, "Abraham Masri" <notifications@github.com> wrote:












Closed #63.

**Comment by XIONGJUNHAN** [comment] 2017-12-26 05:34
How I can do to solve this problem?
		
		

		
	




On Tue, Dec 26, 2017 at 1:29 PM +0800, "Abraham Masri" <notifications@github.com> wrote:












Closed #63.

**Comment by Johntpeterson** [comment] 2017-12-26 05:42
@XIONGJUNHAN Directly from #29: "In line 266, jailbreak.m (extra_recipe), change if(should_install_cydia != YES) { to if(should_install_cydia == YES) {. This fixed it for me on iPhone 7 iOS 11.1.2. If not, I'll take a deeper look into the log for you."

**Comment by XIONGJUNHAN** [comment] 2017-12-26 05:47
@johntpeterson think you ,I know ,do you have the ipa That solve this problem?
